### ISSUE TITLE
how to exclude directories from coverage preprocessor

### ISSUE THREAD

**Issue by chevalric** [karma-runner/karma-coverage#13] opened 2013-08-29 09:21 UTC
Hi, I've been trying for a few hours now to exclude my test dirs from the coverage preprocessor, but I can't seem to find the right pattern. I was wondering if you could help me out.

I have multiple modules, which follow the same basic directory structure:

![screen shot 2013-08-29 at 11 02 45](https://f.cloud.github.com/assets/150461/1048429/5810da04-108c-11e3-8013-6a52339e3a5a.png)

I'm looking for a pattern that will exclude everything in the test directory, but will instrument all the other files in the module (so the javascript-files in de models and views directories should be instrumented as well).

I've tried the following patterns:
src/**/!(test)/**/*.js
src/**/!(test)/*.js
!**/test/**/*.js

When I use that last pattern in a simple file that loads minimatch and test various paths it works as expected. However, when I put that pattern in the karma configuration, I get no files instrumented at all. I've also tried to first include all files, and then use the exclusion pattern to exclude the test files, but that didn't work either.

**Comment by Ashwell** [comment] 2015-02-14 03:01
Thanks @andrezero you helped me! I ended up with `**/!(vendor)/!(*.tests).js` :+1:

**Comment by martin-brennan-csnet** [comment] 2015-03-10 00:35
Thank you! This was annoying me so much, I thought surely someone else was having this problem! My structure was like this:

```
src
- app
    - myComponent
        spec
            - myComponentFactory_spec.js
        - myComponentFactory.js
```

And I used this for the preprocessor:

```
'src/app/**/!(*spec)/*.js': ['coverage']
```

**Comment by Dignifiedquire** [comment] 2015-06-09 15:39
Closing has this is resolved

**Closed by Dignifiedquire** 2015-06-09 15:39 UTC

**Comment by wbecker** [comment] 2015-07-15 22:03
Just as an addendum, I used this issue to solve how I should get the following working:

my `public/js` directory has a `lib/bower` directory that I wanted to ignore, but still wanted `lib/everything_else.js`.

I used the following glob:

`"public/js/{*.js,lib/*.js,lib/!(bower)/**/*.js,!(lib)/**/*.js}"`

Hope this helps someone (or future me) someday!

**Comment by mprentic-harris** [comment] 2015-11-11 14:57
An example of this really needs to be added to the README.md.

**Comment by michaelprescott** [comment] 2015-12-27 23:58
@mprentic-harris: I agree, more examples and suggestions for how to confirm or report selection and exclusion results would be good.  I have mine working like I want now, but honestly it's still a bit counter-intuitive or maybe overloaded.  I think `'app/!(assets)/**/*.js'` reads like "include all js files in the app directory and subdirectories except those in assets sub directory, but my intuition (wrong) tells me it just says exclude js in the assets directory.

**Comment by VWoeltjen** [comment] 2016-01-08 23:26
More examples would be nice, but I really think a better syntax is needed. If the issue is that karma itself only allows a single glob for the preprocessor properties, then it would be nice if there could be some preprocessor configuration properties to filter things down even more, e.g.:

```js
coveragePreprocessor: {
    exclude: [ "**/*.spec.js", "**/vendor/**/*" ]
}
```

I get that this doesn't add much (if any) real capability relative to the current state of things, but it would save some useful brain-time to not have to write/parse esoteric minimatch strings for such a common, conceptually simple thing.

**Comment by allenhwkim** [comment] 2016-02-26 19:01
@VWoeltjen +1

**Comment by shovemedia** [comment] 2016-11-05 01:42
I *need* preprocessing to allow imports in tests, so omitting from preprocessors config is a no go.

I found this buried in an example .babelrc and it works!
  "env": {
    "test": {
      "plugins": [
        ["__coverage__", {"ignore": "*+(test|stub).*"}]
      ]
    }
  }

populating the env var is left as an exercise but more here:
https://github.com/kentcdodds/es6-todomvc/tree/FEM/02.4-cover-everything

**Comment by csvan** [comment] 2017-02-22 14:03
I cannot for the life of me get this to work. My use case is pretty simple - I just want to exclude all files ending in `directive.js`, but this glob simply won't work: `!client/**/*.directive.js`. Any ideas?

**Comment by ashwell** [comment] 2017-02-22 21:59
@csvan you need to put the exclusion on the group you want to exclude not the whole expression.

Without actually testing, off the top of my head I think what you are looking for is
```
src/**/!(*.directive).js
```

**Comment by csvan** [comment] 2017-02-23 10:27
@ashwell thanks, that did not work unfortunately. I am guessing it has something to do with my project setup (I'm using the Karma webpack plugin). Will get back if I find anything.

**Comment by bodawei** [comment] 2017-02-27 03:04
@csvan (et al) I also wish I could do the same thing. Though I don't have an answer, I thought I'd add some color to the comments in this thread:

I created a simple setup like this:

- karma-config.js
- src
   - foo.js
   - test/
       foo2.test.js
   - child/
      - bar.js
      - test/
         - bar.test.js

the source and test files are about as trivial as I could make them.

my karma-config.js file is

```
module.exports = function(config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine'],
    files: [
      'src/**/*.js'
    ],
    preprocessors: {
      // see comments below
    },
    reporters: ['progress', 'coverage'],
    coverageReporter: {
      // whatever settings you like
    }
  })
}
```

So, as others have commented, I found I could do this to exclude whole directories
- 'src/{**/!(test)/\*.js,\*.js}': ['coverage']

However, I could not find any way to exclude files using !() kinds of expressions.  Some expressions had truly surprising results.  This one, for example, excluded the test directories, but not `src/foo.test.js`
- 'src/{**/!(\*.test).js,\*.js}': ['coverage']

While this one included all the files and directories
-  'src/**/{!(\*test.js),\*.js}': ['coverage']

Those last two are not doing what I'd expect. So, clearly, my mental model of the syntax and the implementation of the syntax are not the same.  I delved a bit into karma's code and found that in `karma/lib/preprocessor.js` it is simply calling minimatch (mm) to decide what to do with these:
-           if (mm(file.originalPath, patterns[i], {dot: true})) {

So, ultimately the full answer here is someone needs to read through the [minimatch source code](https://github.com/isaacs/minimatch/blob/master/minimatch.js) and figure out what it's doing.  The documentation for the project is sparse enough that probably reading the source is faster.  I've run out of time this evening, so am just recording my notes here for folks in the future.

**Comment by wawyed** [comment] 2017-03-03 09:18
I have the exact same problem as @bodawei . I'm trying to exclude my spec.js files from my coverage report but I cannot find a way of doing it without changing the folder structure.

**Comment by wawyed** [comment] 2017-03-03 13:36
After trying some of the solutions mentioned on this issue I managed to get the desired behavior by doing:

``` javascript
    preprocessors: {
      'src/**/*.html': ['ng-html2js'],
      'src/**/*.js': ['coverage'],
      'src/**/!(*.spec).ts': ['karma-typescript', 'coverage'],  //<-- Ignore spec for coverage
      'src/**/*.spec.ts': ['karma-typescript']
    },
```

**Comment by bodawei** [comment] 2017-03-04 19:03
@wawyed good job! Your solution of including everything 

```
'src/**/*.js': ['coverage'],
```

and then removing some things that aren't wanted

```
'src/**/!(*.spec).ts': ['coverage'], 
```

worked for me as well.  Nice.

**Comment by csvan** [comment] 2017-03-05 11:24
Unfortunately @wawyed solution did not work for me, though I have an almost identical setup:

```
preprocessors: {
    'spec.js': ['webpack'],
    'client/**/*.js': ['coverage'],
    'client/**/!(*.directive).js': ['coverage']
  },
```

The reports will still contain coverage for `directive.js` files. I am wondering if there is a collision with `karma-webpack` at some point.

**Comment by wawyed** [comment] 2017-03-05 11:44
@csvan that's because of the second line.

Try like this:
``` javascript

preprocessors: {
    'spec.js': ['webpack'],
    'client/**/!(*.directive).js': ['coverage']
  },
```


That should do coverage for everything expect directive.js

**Comment by csvan** [comment] 2017-03-05 12:28
@wawyed tried that already, does not work unfortunately.

**Comment by bodawei** [comment] 2017-03-09 05:40
@csvan Actually, I find if I make the change wawyed suggested, it works for me (I don't have webpack in there at all, though. Just the line for coverage).  I'm a bit puzzled as I thought having that line ( 'src/**/*.js': ['coverage'], ) was necessary, but now I see it gets in the way.  not sure what I was smoking.

What version of karma are you using?

**Comment by csvan** [comment] 2017-03-10 06:39
@bodawei I am using the latest versions of both Karma and this plugin.

However, I am almost certain that the problem is not with either, but rather another plugin, `karma-webpack`. This plugin uses webpack to compile the project and all tests into a single monolithic .js file which is then executed. That may be why things are breaking.

However, I am still getting accurate coverage reports for each and every js file in the project, in its original location in the project structure, so clearly coverage information is being correctly generated. I simply cannot choose which files to exclude.

**Comment by jschraub** [comment] 2017-05-12 22:47
@csvan I am running into the same situation.  Have you found a solution to this?  Would love to solve this so that I can get cleaner coverage reports.

**Comment by csvan** [comment] 2017-05-15 19:58
@jschraub in my case, it ultimately turned out to be an issue with the Webpack Istanbul plugin - I had to configure it specifically not to touch the files I wanted to exclude. Fiddling with the Karma config did nothing at all.

**Comment by gempi** [comment] 2017-05-18 19:46
@csvan did you try something like this?
```
'src/**/*[^.config].ts': ['coverage']
```
