### ISSUE TITLE
Error using 0.5.4

### ISSUE THREAD

**Issue by thatguyandy27** [karma-runner/karma-coverage#218] opened 2016-03-03 15:08 UTC
After installing the newest version of karma-coverage (0.5.4), I now receive an error trying to use the plugin.  The error from the console is pasted below.  I have reverted back to version 0.5.3, and that works fine.  

-Andy 

> 03 03 2016 09:03:13.333:WARN [reporter]: Can not load "coverage"!
>   TypeError: Cannot read property 'browser' of undefined
>     at new InMemoryReport (/Users/ameyers/stash/gh-toolkit/gh-menu-components/node_modules/karma-coverage/lib/in-memory-report.js:3:21)
>     at Object.Factory.create (/Users/ameyers/stash/gh-toolkit/gh-menu-components/node_modules/karma-coverage/node_modules/istanbul/lib/util/factory.js:48:16)
>     at /Users/ameyers/stash/gh-toolkit/gh-menu-components/node_modules/karma-coverage/node_modules/istanbul/lib/report/common/defaults.js:40:30
>     at Array.forEach (native)
>     at Object.module.exports.defaultReportConfig (/Users/ameyers/stash/gh-toolkit/gh-menu-components/node_modules/karma-coverage/node_modules/istanbul/lib/report/common/defaults.js:39:32)
>     at Object.defaultConfig (/Users/ameyers/stash/gh-toolkit/gh-menu-components/node_modules/karma-coverage/node_modules/istanbul/lib/config.js:60:47)
>     at new CoverageReporter (/Users/ameyers/stash/gh-toolkit/gh-menu-components/node_modules/karma-coverage/lib/reporter.js:49:58)
>     at invoke (/Users/ameyers/stash/gh-toolkit/gh-menu-components/node_modules/karma/node_modules/di/lib/injector.js:75:15)
>     at Array.instantiate (/Users/ameyers/stash/gh-toolkit/gh-menu-components/node_modules/karma/node_modules/di/lib/injector.js:59:20)
>     at get (/Users/ameyers/stash/gh-toolkit/gh-menu-components/node_modules/karma/node_modules/di/lib/injector.js:48:43)
>     at /Users/ameyers/stash/gh-toolkit/gh-menu-components/node_modules/karma/lib/reporter.js:104:75
>     at Array.forEach (native)
>     at createReporters (/Users/ameyers/stash/gh-toolkit/gh-menu-components/node_modules/karma/lib/reporter.js:92:9)
>     at Array.invoke (/Users/ameyers/stash/gh-toolkit/gh-menu-components/node_modules/karma/node_modules/di/lib/injector.js:75:15)
>     at get (/Users/ameyers/stash/gh-toolkit/gh-menu-components/node_modules/karma/node_modules/di/lib/injector.js:48:43)
>     at get (/Users/ameyers/stash/gh-toolkit/gh-menu-components/node_modules/karma/node_modules/di/lib/injector.js:54:19)

**Comment by dignifiedquire** [comment] 2016-03-03 15:43
Thanks for the report, @nicojs could you take a look, looks like this has sth to do with your new code.

**Comment by nicojs** [comment] 2016-03-03 17:03
Indeed this has to do with my beloved in-memory reporter. I'm trying to figure out what the problem is. It seems that the `in-memory` reporter is used but the options passed through are undefined.

@thatguyandy27 could you add more detailed information? At least the karma.config used, preferably a repository that reproduces the error.

**Comment by thatguyandy27** [comment] 2016-03-03 17:09
I attached the karma.config.  The repo isn't available publicly so I would have to spend some time creating one with a similar set-up.  I can do that if if you need me to, but I probably wouldn't be able to start on it until 6/7 PM (CST). 

[karma.conf.js.txt](https://github.com/karma-runner/karma-coverage/files/157262/karma.conf.js.txt)

**Comment by bencoveney** [comment] 2016-03-03 17:25
Another stack trace and config file if it is helpful to you :)

`[16:56:03] TypeError: Cannot read property 'browser' of undefined
at new InMemoryReport (path_to_node_modules\karma-coverage\lib\in-memory-report.js:3:21)
at Object.Factory.create (path_to_node_modules\istanbul\lib\util\factory.js:48:16)
at path_to_node_modules\istanbul\lib\report\common\defaults.js:40:30
at Array.forEach (native)
at Object.module.exports.defaultReportConfig (path_to_node_modules\istanbul\lib\report\common\defaults.js:39:32)
at defaultConfig (path_to_node_modules\istanbul\lib\config.js:60:47)
at new Configuration (path_to_node_modules\istanbul\lib\config.js:377:37)
at Object.loadFile (path_to_node_modules\istanbul\lib\config.js:439:12)
at Gulp.<anonymous> (C:\Builds\4\SCRUM Training\SfooP\src\SfooP\SfooP\gulpfile.js:54:31)
at module.exports (path_to_node_modules\orchestrator\lib\runTask.js:34:7)
at Gulp.Orchestrator._runTask (path_to_node_modules\orchestrator\index.js:273:3)
at Gulp.Orchestrator._runStep (path_to_node_modules\orchestrator\index.js:214:10)
at path_to_node_modules\orchestrator\index.js:279:18
at finish (path_to_node_modules\orchestrator\lib\runTask.js:21:8)
at cb (path_to_node_modules\orchestrator\lib\runTask.js:29:3)
at removeAllListeners (path_to_node_modules\karma\lib\server.js:336:7)`

[karma.conf.js.txt](https://github.com/karma-runner/karma-coverage/files/157300/karma.conf.js.txt)

**Comment by nicojs** [comment] 2016-03-03 19:11
Unfortunately, I couldn't reproduce it. The stacktrace was pretty clear though, so i created a pull request. Apparently Istanbul creates an instance of the Report without supplying the arguments. Could one of you verify that the issue is solved?

**Comment by tjsail33** [comment] 2016-03-03 21:39
+1, all of our CI jobs are failing as of 9 hours ago.

**Comment by thatguyandy27** [comment] 2016-03-04 01:25
@nicojs I was able to create it just now using this repo [https://github.com/thatguyandy27/karma-coverage-sandbox](url).  To recreate it you should just be able to clone it, run npm install, and then npm test.  You should see the error in your console.

**Comment by fluky** [comment] 2016-03-04 01:28
Getting the same here.  I can confirm that the PR fixes it for me.

**Comment by FJLopezGarcia** [comment] 2016-03-07 10:05
Hi @nicojs i am having the same issue... with version "karma-coverage": "^0.5.3", and "karma-coverage": "^0.5.4".... it was working perfectly some days ago with 0.5.3

```javascript
07 03 2016 10:40:01.115:WARN [reporter]: Can not load "coverage"!
  TypeError: Cannot read property 'browser' of undefined
    at new InMemoryReport (/Users/francisco/TBD.Web/node_modules/karma-coverage/lib/in-memory-report.js:3:21)
    at Object.Factory.create (/Users/francisco/TBD.Web/node_modules/karma-coverage/node_modules/istanbul/lib/util/factory.js:48:16)
    at /Users/francisco/TBD.Web/node_modules/karma-coverage/node_modules/istanbul/lib/report/common/defaults.js:40:30
    at Array.forEach (native)
    at Object.module.exports.defaultReportConfig (/Users/francisco/TBD.Web/node_modules/karma-coverage/node_modules/istanbul/lib/report/common/defaults.js:39:32)
    at Object.defaultConfig (/Users/francisco/TBD.Web/node_modules/karma-coverage/node_modules/istanbul/lib/config.js:60:47)
    at new CoverageReporter (/Users/francisco/TBD.Web/node_modules/karma-coverage/lib/reporter.js:49:58)
    at invoke (/Users/francisco/TBD.Web/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at Array.instantiate (/Users/francisco/TBD.Web/node_modules/karma/node_modules/di/lib/injector.js:59:20)
    at get (/Users/francisco/TBD.Web/node_modules/karma/node_modules/di/lib/injector.js:48:43)
    at /Users/francisco/TBD.Web/node_modules/karma/lib/reporter.js:104:75
    at Array.forEach (native)
    at createReporters (/Users/francisco/TBD.Web/node_modules/karma/lib/reporter.js:92:9)
    at Array.invoke (/Users/francisco/TBD.Web/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at get (/Users/francisco/TBD.Web/node_modules/karma/node_modules/di/lib/injector.js:48:43)
    at get (/Users/francisco/TBD.Web/node_modules/karma/node_modules/di/lib/injector.js:54:19)
```

**Comment by dignifiedquire** [comment] 2016-03-07 10:59
This is fixed in #219, will release a new version today.

**Closed** 2016-03-07 11:57 UTC
Labels: PR exists, type: bug

**Comment by thatguyandy27** [comment] 2016-03-09 14:50
Thanks @dignifiedquire & @nicojs.  New version works like a charm.

**Comment by FJLopezGarcia** [comment] 2016-03-09 18:53
yes, thanks!!
