### ISSUE TITLE
karma coverage does not show any data

### ISSUE THREAD

**Issue by priyabrat1801** [karma-runner/karma-coverage#87] opened 2014-07-10 23:04 UTC
I have included the source files in the files & preprocessors section of my karma conf file. The tests run fine and the junit xml report shows the data. The html coverage just show 100% without any data. I have the similar structure for another project which is working fine but not this one. Not sure if i am missing something. Might be a very minor or silly thing i have missed.

karma.conf.js:

        module.exports = function (config) {
        config.set({
        basePath: '../../',
        
        frameworks: [
            'jasmine'
        ],

        // list of files / patterns to load in the browser
        files: [
            'app/js/**/*.js',
            'test/spec/**/*.js'
        ],

        preprocessors: {
            'app/js/**/*.js': ['coverage']
        },

        exclude: [],

        reporters: [ 'progress', 'junit', 'coverage' ],

        coverageReporter: {
            type: 'html',
            dir: 'test/reports/unit/coverage'
        },

        junitReporter: {
            outputFile: 'test/reports/unit/junit/junit.xml',
            suite: 'unit'
        },

        port: 9876,

        runnerPort: 9100,

        colors: true,

        logLevel: config.LOG_DEBUG,

        autoWatch: false,

        browsers: [ 'Chrome' ],

        captureTimeout: 60000,

        singleRun: true
    });
    };

my karma conf file is in test -> spec -> conf
and source files are in app -> js -> controllers/directives/services

the debug log shows its loading all the files in preprocessors but the report does not show any data "No data to display".

**Comment by johnpapa** [comment] 2015-01-09 13:06
+1 as I am also seeing 100% coverage with no files though I have 52 passing tests.

Any new news on this?

```
INFO [karma]: Karma v0.12.28 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.7 (Mac OS X)]: Connected on socket ovcuUFjTOjYXDhS4x036 with id 33832217
PhantomJS 1.9.7 (Mac OS X): Executed 52 of 52 SUCCESS (0.088 secs / 0.026 secs)
----------|-----------|-----------|-----------|-----------|
File      |   % Stmts |% Branches |   % Funcs |   % Lines |
----------|-----------|-----------|-----------|-----------|
----------|-----------|-----------|-----------|-----------|
All files |       100 |       100 |       100 |       100 |
----------|-----------|-----------|-----------|-----------|


=============================== Coverage summary ===============================
Statements   : 100% ( 0/0 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 0/0 )
Lines        : 100% ( 0/0 )
```

**Comment by johnpapa** [comment] 2015-01-09 13:32
Turns out it was the minimatch and the file exclusions, which is what I thought (and feared). Glob patterns or even regex (gasp) would be more straightforward.

this ended up solving my problem, to exclude .spec.js files

```
./src/client/app/**/!(*.spec)+(.js)': ['coverage']
```

**Comment by dhrubach** [comment] 2015-02-04 23:59
+1 same issue here. Empty coverage report generated for both chrome 40.0.2214 and PhantomJS 1.9.8.

karma.conf.js

<code>
module.exports = function(config) {
  config.set({
      
      basePath: '',
      
      frameworks: ['requirejs', 'mocha', 'chai-sinon'],

      plugins: [
         'karma-mocha',
         'karma-requirejs',
         'karma-chrome-launcher',
         'karma-phantomjs-launcher',
         'karma-chai-sinon',
         'karma-mocha-reporter',
         'karma-clear-screen-reporter',
         'karma-coverage'
      ],

      // list of files / patterns to load in the browser
      files: [
          'test/test-odyssey-main.js',
           all source and spec files
      ],

      // list of files to exclude
      exclude: [
          'lib/**/*.json',
          'config.js',
          'main.js'
      ],

      // preprocess matching files before serving them to the browser
      preprocessors: {
          'app/**/*.js': ['coverage']
      },

      // test results reporter to use
      reporters: ['mocha', 'clear-screen', 'coverage'],

      // reporter options 
      mochaReporter: {
		output: 'full'
	  },	

      coverageReporter: {
          type: 'html',
          dir: 'coverage/'
      },

      // web server port
      port: 9876,

      // enable / disable colors in the output (reporters and logs)
      colors: true,

      // level of logging
      logLevel: config.LOG_DEBUG,

      // enable / disable watching file and executing tests whenever any file changes
      autoWatch: true,

      // start these browsers
      browsers: ['PhantomJS', 'Chrome'],
      
      singleRun: false
  });
};
</code>

node v0.10.35
npm v1.4.28
karma v0.12.31
karma-coverage 0.2.7

In debug.html, I do see that the source code under test is instrumented. However the generated report is blank with 'No data to display'. I have tried all possible suggestions so far, still no luck.

Is there a way i can debug reporter ?

**Comment by dhrubach** [comment] 2015-02-05 04:51
The issue was resolved after altering the order of loading files as explained at http://stackoverflow.com/questions/26850684/karma-coverage-requirejs-misleading-coverage-reports. Keeping the above configuration as is, I changed test-main.js to the following - 

```
var allTestFiles = [];
var allSourceFiles = [];
var testRegexp = /(Spec.mocha)\.js$/im;
var srcRegexp = /app\/[a-zA-Z]+\/[a-zA-Z]+.js$/im;

var normalizePathToSpecFiles = function (path) {
    return path.replace(/^\/base\//, '../').replace(/\.js$/, '');
};

var normalizePathToSourceFiles = function (path) {
    return path.replace(/^\/base\/app\//, '').replace(/\.js$/, '');
};

var loadSourceModulesAndStartTest = function() {
    require(allSourceFiles, function () {
        require(allTestFiles, function () {
            window.__karma__.start();
        });
    });
};

Object.keys(window.__karma__.files).forEach(function (file) {
    if (testRegexp.test(file)) {
        allTestFiles.push(normalizePathToSpecFiles(file));
    } else if (srcRegexp.test(file)) {
        allSourceFiles.push(normalizePathToSourceFiles(file));
    }
});

require.config({

    baseUrl: '/base/lib',

    paths: {
       all file paths
    },

    shim: {
        angular: {
            exports: 'angular'
        },
        angularui: ['angular'],
        "bootstrap.min": ['jquery']
    },

    deps: ['angular', 'jquery', 'bootstrap.min'],

    callback: loadSourceModulesAndStartTest
});
```

**Comment by shystruk** [comment] 2015-04-28 10:33
Hello everyone!
The same problem (

Did example on top helps for anybody ?

**Comment by mhelvens** [comment] 2015-05-04 10:48
I'm not sure if I'm experiencing exactly the same thing. Using karma-coverage ~0.3, my lcov.info ends up empty, though the 'text-summary' reporter works properly. When I downgrade to karma-coverage ~0.2, everything works properly again. I thought it might be a regression of https://github.com/karma-runner/karma/issues/892?

**Comment by bittorture** [comment] 2015-05-06 09:49
Don't know if this will help anyone but I was testing a service which has a method 'destroy' within a describe('destroy()', function(){}).  This caused exactly this issue running with the coverage plugin.

PhantomJS 1.9.7 (Linux) ERROR
  Some of your tests did a full page reload!
PhantomJS 1.9.7 (Linux): Executed 491 of 493 ERROR (2.049 secs / 2.031 secs)

    plugins: [
      'karma-phantomjs-launcher',
      'karma-jasmine',
      'karma-junit-reporter',
      'karma-coverage',
      'karma-ng-html2js-preprocessor'
    ]

Renaming the suite fixed the issue.

**Comment by jodytate** [comment] 2015-05-21 22:32
i can confirm @mhelvens report: running karma-coverage ~0.3 produces the `100% ( 0/0 )` reports, but downgrading to ~0.2 returns a coverage report as expected.

**Comment by Dignifiedquire** [comment] 2015-06-09 15:10
Does anyone have a repo that reproduces this issue consistently?

**Comment by anshbansal** [comment] 2015-06-14 13:25
My repo has this issue
https://github.com/anshbansal/linksharing2

Run this using the command 
karma start grails-app/conf/karma.conf.js --no-auto-watch --single-run --browsers PhantomJS

**Comment by anshbansal** [comment] 2015-06-16 03:01
bump

**Comment by Dignifiedquire** [comment] 2015-06-16 07:43
thanks @anshbansal I will try to take a look as soon as I can

**Comment by andy-dorman** [comment] 2015-06-17 10:10
I'm not totally sure how related this is but after running into the same issues as others on this thread I looked back into a project I worked on that had this working.

The vital config for me was to require browserify-istanbul in my karma.config.js:

    var istanbul = require("browserify-istanbul");

and set this config:

    browserify: {
      global: true,
      debug: true,
      fullPaths: false,
      transform: [
        [
          istanbul({
          ignore: ["node_modules/**", "client/app/**/*.spec.js"],
          includeUntested: false
          }),
          { global: true }
        ]
      ]
    }

Not totally sure what this points to other than a possible issue with karma-browserify perhaps, but maybe it can help someone...

**Comment by qiu8310** [comment] 2015-06-22 09:09
+1 some issue in my repo

**Comment by jperry** [comment] 2015-07-10 14:40
It's been 18 days an no update on this issue.  Any resolution to this as it seems a lot of people including myself get zero results for code coverage.

**Comment by Dignifiedquire** [comment] 2015-07-10 15:35
@anshbansal the repro, was not a real repro I'm afraid, the issue was that the coverage preprocessor was not properly matching any files: https://github.com/anshbansal/linksharing2/pull/1

@jperry I'm sorry, that it's not working for you, but I'm working alone on all of karma, mostly at nights, and the coverage reporter is not something I use at all, so while I do understand that you are frustrated about it not working, please be a bit more constructive and maybe try figuring out yourself where the issue lies.

**Comment by Dignifiedquire** [comment] 2015-07-10 15:45
@qiu8310 posted in your repo, not seeing an issue there

**Comment by jperry** [comment] 2015-07-10 16:37
@Dignifiedquire -sorry about that.  I have been looking at it all morning and haven't found how to fix it.  Here is my karma.conf.js
```
// Karma configuration
// Generated on Thu Jul 09 2015 16:02:40 GMT-0400 (EDT)

module.exports = function(config) {
  config.set({

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '',


    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['jasmine'],


    // list of files / patterns to load in the browser
    files: [
      'spec/**/*.spec.js'
    ],


    // list of files to exclude
    exclude: [
    ],


    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
      // source files, that you wanna generate coverage for
      // do not include tests or libraries
      // (these files will be instrumented by Istanbul)
      './routes/**/*.js': ['coverage'],
      './app.js': ['coverage']
    },


    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ['progress', 'coverage'],

    // optionally, configure the reporter
    coverageReporter: {
      dir: 'build/reports/coverage',
      reporters: [
        // reporters not supporting the `file` property
        { type: 'html', subdir: 'report-html' },
        { type: 'lcov', subdir: 'report-lcov' }
      ]
    },

    // web server port
    port: 9876,


    // enable / disable colors in the output (reporters and logs)
    colors: true,


    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_INFO,


    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: true,


    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: ['PhantomJS'],


    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: false
  })
}
```
My devDependencies are like so:
```
  "devDependencies": {
    "gulp": "^3.9.0",
    "karma": "^0.12.37",
    "karma-coverage": "^0.4.2",
    "karma-jasmine": "^0.2.2",
    "karma-phantomjs-launcher": "^0.2.0",
    "phantomjs": "^1.9.17"
  }
```

My project is pretty small
```
node_modules/
routes/
spec/
app.js
karma.conf.js
package.json
```

Maybe I'm missing something obvious in my file patterns.

**Comment by Dignifiedquire** [comment] 2015-07-10 17:08
I think the issues is that you are missing the source files, in the `files` array, try something like this:

```js
files: [
  'app.js',
  'routes/**/*.js',
  'spec/**/*.spec.js'
],
```

**Comment by jperry** [comment] 2015-07-10 17:22
@Dignifiedquire - I did try that before and I got this:

```
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: require
  at /Users/jayperry/workspace/myapp/app.js:9


[13:21:36] 'test' errored after 1.65 s
[13:21:36] Error: 1
    at formatError (/Users/jayperry/.nvm/v0.10.33/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/Users/jayperry/.nvm/v0.10.33/lib/node_modules/gulp/bin/gulp.js:195:15)
```

**Comment by Dignifiedquire** [comment] 2015-07-10 17:29
Hmm, strange, any chance you could give me temporary access to the code?

**Comment by jperry** [comment] 2015-07-10 18:17
@Dignifiedquire - sorry I can't.  I could try stripping a bunch out and leave some boilerplate code in there.

**Comment by jperry** [comment] 2015-07-13 18:36
@Dignifiedquire - I created a simple [repository](https://github.com/jperry/node-karma) to show one that doesn't generate results.

**Comment by Dignifiedquire** [comment] 2015-07-13 19:05
@jperry thanks, I think I know what the issue is. So the setup you have is an express app, that serves up some routes, and then you want to test those routes through karma. But this will not work with `karma-coverage`, as it is only able to handle and instrument the browser side part, as karma itself only runs in the browser. From the looks of the repo you should try something like using istanbul on its own, together with a library like https://github.com/visionmedia/supertest to test the routes and get test coverage.

**Comment by jperry** [comment] 2015-07-13 21:29
@Dignifiedquire - thank you.  We actually did as you suggested and used jasmine and istanbul directly.  We are now getting code coverage reports.  Thanks for the tip.

**Comment by Dignifiedquire** [comment] 2015-07-14 08:54
@jperry glad to hear. 

Closing, as this issue has been resolved, and the remaining issues seem to be configuration problems.

**Closed by Dignifiedquire** 2015-07-14 08:54 UTC
Labels: support

**Comment by urbaitel** [comment] 2015-10-13 22:34
I found an issue with order of reporters.  Try this and it will work!

coverageReporter: {
      dir: 'reports/coverage/',
      reporters: [
        { type: 'lcov', subdir: '.' },
        { type: 'text-summary' },
        { type: 'text' },
        { type: 'cobertura', subdir: '.', file: 'coverage.xml' }
      ],
      instrumenters: {isparta: require('isparta')},
      instrumenter: {
        'src/**/!(spec)*.js': 'isparta'
      }
    },

**Comment by BrainSlugs83** [comment] 2015-10-14 01:11
I have this issue with latest -- I'm only using one reporter -- it doesn't seem to be a configuration problem -- I can resolve the issue with the hack to test-main.js that was posted by @dhrubach.

**Comment by Nocomm** [comment] 2016-01-22 18:36
Is there a problem with karma-coverage itself, or with using it in conjunction with other npm modules?  Wasn't @dhrubach 's fix for compatibility with RequireJS?

**Comment by j-funk** [comment] 2016-03-02 05:06
@andy-dorman thank you, was using Browserify (with Grunt & Karma) - your note got me up and running!

**Comment by joeSaad** [comment] 2016-08-30 17:09
I've been having the same issue. tried all solutions in here. I'm using webpack, karma, jasmine and been trying to generate coverage report to no avail. It's been coming out empty.

**Comment by surfjedi** [comment] 2016-10-11 19:15
+1

**Comment by dannycallaghan** [comment] 2016-10-19 13:53
+1

Same for me. Using webpack, karma, jasmine. If I choose to show the coverage output in the console, it works fine. If I choose to output as html, the html is generated, but it shows 100% (0/0) for everything, and doesn't display any data in the table below.

**Comment by stsvilik** [comment] 2016-10-20 03:43
I've has similar issue with browserify + babel + karma. Take a look [here](https://github.com/istanbuljs/babel-plugin-istanbul).

Key to my setup was to add ["istanbul"] into babel plugins.

**Comment by hzhu** [comment] 2016-10-31 07:11
Had this issue too, 0/0 and 100% test coverage. Adding "coverage" ti the preprocessor array fixed it for me:

```
    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
      // add webpack as preprocessor
      '../../src/*test.js': ['webpack', 'coverage'],
      '../../src/**/*test.js': ['webpack', 'coverage'],
    },
```

**Comment by surfjedi** [comment] 2016-11-01 13:22
that worked! thanks @stsvilik thanks!

**Comment by CATIGERN** [comment] 2016-11-08 13:15
I was facing the same issue. My Debug Log showed that files were being processed, however a coverage report was not being generated.
I solved this by setting the includeAllSources flag to true in my coverageReporter. Hope that helps!

`
 coverageReporter: {
      dir: 'report/',
      includeAllSources: true
    },
`

**Comment by megamindbrian** [comment] 2017-06-12 20:13
For some reason all these tutorial are missing the part about the entirely separate webpack plugin: istanbul-instrumenter-loader.  So I am dropping it here for consistency.  Setting up webpack with istanbul-instrumenter-loader set me on the right track.

**Comment by yancwa** [comment] 2017-10-30 07:42
@CATIGERN , thanks very much, it helps a lot, finally it works,hahahah

**Comment by Alendorff** [comment] 2018-01-22 15:18
Hello there from 2018. 

Sorry for archeology, but I have just migrated from phantomjs to [puppeteer](https://github.com/GoogleChrome/puppeteer) and faced with that issue. I work with webstorm and usualy it happens when I run single test suite. WS then show me this message as below and doesn't show coverage info to me. Absolutely random thing. Sometimes I get coverage, sometimes - not. 

Cannot find karma test coverage report - lcov.info
![Cannot find karma test coverage report - lcov.info](https://user-images.githubusercontent.com/4989157/35227325-7c8a8fda-ff96-11e7-873f-38bfe41d344f.png)


```
    "grunt-karma": "^2.0.0",
    "jasmine-core": "^2.8.0",
    "karma": "^1.7.1",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "^1.0.1",
    "karma-coverage": "^1.1.1",
    "karma-jasmine": "^1.1.1",
    "puppeteer": "^0.13.0"
```

**Comment by ThomasR** [comment] 2018-02-28 10:45
I ran into this issue when using rollup + babel + karma.

I fixed it by using `"istanbul"` as a babel plugin, as suggested [above](
https://github.com/karma-runner/karma-coverage/issues/87#issuecomment-255001800).

Then, use babel as a karma plugin, and do **not** include `rollup-plugin-istanbul`.

```
config.set({
  preprocessors: {
    'test/**/*.js': ['rollup']
  },
  plugins: [
    …
    babel({
      plugins: [
        [
          'transform-react-jsx',
          {
            pragma: 'createElement'
          }
        ],
        'istanbul'
      ]
    })
    …]
  ]
  …
}
```

**Comment by djlxiaoshi** [comment] 2018-05-24 04:01
if you use webpack or other utils to transform your sourcecode use should use **istanbul** before

**Comment by abizebel** [comment] 2018-06-20 11:32
hi friend
just change  preprocessor to 
preprocessors: {
    '**/*.js': 'coverage'
},
100% will solve your problem

**Comment by raxxarr** [comment] 2024-12-31 16:04
[this](https://github.com/karma-runner/karma-coverage/issues/87#issuecomment-255001800) works, if you use webpack, here is an example config:

```js
module.exports = function(config) {
  config.set({
    frameworks: ['mocha', 'webpack'],
    files: [
      { pattern: 'test/**/*.js', watched: false },
      { pattern: 'src/**/*.js', watched: false },
    ],
    preprocessors: {
      'test/**/*.js': ['webpack'],
      'src/**/*.js': ['webpack'] // no coverage here
    },
    reporters: ['mocha', 'coverage'],
    webpack: {
      module: {
        rules: [
          {
            test: /\.(?:js|mjs|cjs)$/,
            exclude: /node_modules/,
            use: {
              loader: 'babel-loader',
              options: {
                targets: "defaults",
                presets: [
                  ['@babel/preset-env']
                ],
                plugins: ['istanbul'] // <<< add istanbul here
              }
            }
          }
        ]
      }
    },
  })
}
```
install some dependencies if you don't have:
```shell
npm install -D babel-loader @babel/core @babel/preset-env babel-plugin-istanbul
```
