### ISSUE TITLE
Allow including all source files in coverage reports

### ISSUE THREAD

**Issue by tannermeans** [karma-runner/karma-coverage#125] opened 2015-01-13 00:05 UTC
Istanbul merged this PR on Dec 4, 2014. It allows files that have no associated tests to be reported as 0% covered. This is a really nice way to figure out where your gaps are and get a more realistic view of your coverage metrics.
https://github.com/gotwarlost/istanbul/pull/275

It would be a great  benefit to allow this functionality in karma-coverage. Currently only code that is required by a test is reported.

**Comment by jorisvddonk** [comment] 2015-02-03 06:45
+1. This is fairly important when dealing with large codebases with many changesets applied every day; eventually some tests are forgotten to be written and you don't really have a good way of noticing that.

Looking at the merged PR, it seems that this feature is enabled in Istanbul by specifying a config variable, so it may be fairly easy to add an option to karma-coverage which forwards this option on to Istanbul itself. The only question then is: can this feature also be implemented for the Coffeescript instrumenter, Ibrik.

**Comment by mattfysh** [comment] 2015-03-22 05:27
As a temporary workaround until this issue is fixed: https://www.npmjs.com/package/karma-coverage-allsources

**Closed** 2015-03-24 08:30 UTC

**Comment by shaikhspear16** [comment] 2016-05-05 15:24
almost a year down, are we able to figure out ? should I go ahead with using  https://www.npmjs.com/package/karma-coverage-allsources?
 how stable is it

**Comment by mattfysh** [comment] 2016-05-06 01:33
we've been using it here at Medallia for over a year... it's a fairly small & lightweight shim. if you ever have any trouble using it, feel free to get in touch with us! https://github.com/medallia

**Comment by jseminck** [comment] 2016-08-12 08:05
Any update on this? `karma-coverage-allsources` does the trick for us as well but it would be nice to see this included inside `karma-coverage`. Thanks!

**Comment by sontek** [comment] 2016-08-20 21:25
@jseminck How did you get `karma-coverage-allsources` to work? I'm getting:

```
20 08 2016 17:22:45.274:INFO [karma]: Karma v1.2.0 server started at http://localhost:9876/
20 08 2016 17:22:45.277:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
20 08 2016 17:22:45.280:INFO [launcher]: Starting browser PhantomJS
20 08 2016 17:22:45.820:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket /#3BPdug1Pg74n-67lAAAA with id 94353108
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 1 of 1 SUCCESS (0.014 secs / 0.008 secs)
Missing error handler on `socket`.
Error: Line 1: Unexpected token
    at createError (/Users/sontek/src/eventray/node_modules/karma-coverage-allsources/node_modules/esprima/esprima.js:2392:21)
    at unexpectedTokenError (/Users/sontek/src/eventray/node_modules/karma-coverage-allsources/node_modules/esprima/esprima.js:2467:13)
    at tolerateUnexpectedToken (/Users/sontek/src/eventray/node_modules/karma-coverage-allsources/node_modules/esprima/esprima.js:2476:21)
    at parseStatementListItem (/Users/sontek/src/eventray/node_modules/karma-coverage-allsources/node_modules/esprima/esprima.js:3926:21)
    at parseFunctionSourceElements (/Users/sontek/src/eventray/node_modules/karma-coverage-allsources/node_modules/esprima/esprima.js:4766:23)
    at parseFunctionExpression (/Users/sontek/src/eventray/node_modules/karma-coverage-allsources/node_modules/esprima/esprima.js:4972:16)
    at parsePrimaryExpression (/Users/sontek/src/eventray/node_modules/karma-coverage-allsources/node_modules/esprima/esprima.js:3232:24)
    at inheritCoverGrammar (/Users/sontek/src/eventray/node_modules/karma-coverage-allsources/node_modules/esprima/esprima.js:2648:18)
    at parseLeftHandSideExpressionAllowCall (/Users/sontek/src/eventray/node_modules/karma-coverage-allsources/node_modules/esprima/esprima.js:3373:20)
    at inheritCoverGrammar (/Users/sontek/src/eventray/node_modules/karma-coverage-allsources/node_modules/esprima/esprima.js:2648:18)
    at parsePostfixExpression (/Users/sontek/src/eventray/node_modules/karma-coverage-allsources/node_modules/esprima/esprima.js:3449:16)
    at parseUnaryExpression (/Users/sontek/src/eventray/node_modules/karma-coverage-allsources/node_modules/esprima/esprima.js:3509:20)
    at inheritCoverGrammar (/Users/sontek/src/eventray/node_modules/karma-coverage-allsources/node_modules/esprima/esprima.js:2648:18)
    at parseBinaryExpression (/Users/sontek/src/eventray/node_modules/karma-coverage-allsources/node_modules/esprima/esprima.js:3598:16)
    at inheritCoverGrammar (/Users/sontek/src/eventray/node_modules/karma-coverage-allsources/node_modules/esprima/esprima.js:2648:18)
    at parseConditionalExpression (/Users/sontek/src/eventray/node_modules/karma-coverage-allsources/node_modules/esprima/esprima.js:3655:16)
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  Disconnectedundefined
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 1 of 1 SUCCESS (0.014 secs / 0.008 secs)
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  Disconnected, because no message in 10000 ms.
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 1 of 1 DISCONNECTED (10.016 secs / 0.008 secs)
20 08 2016 17:22:56.036:ERROR [karma]: { Error: Line 1: Unexpected token
    at createError (/Users/sontek/src/eventray/node_modules/karma-coverage-allsources/node_modules/esprima/esprima.js:2392:21)
    at unexpectedTokenError (/Users/sontek/src/eventray/node_modules/karma-coverage-allsources/node_modules/esprima/esprima.js:2467:13)
    at tolerateUnexpectedToken (/Users/sontek/src/eventray/node_modules/karma-coverage-allsources/node_modules/esprima/esprima.js:2476:21)
    at parseStatementListItem (/Users/sontek/src/eventray/node_modules/karma-coverage-allsources/node_modules/esprima/esprima.js:3926:21)
    at parseFunctionSourceElements (/Users/sontek/src/eventray/node_modules/karma-coverage-allsources/node_modules/esprima/esprima.js:4766:23)
    at parseFunctionExpression (/Users/sontek/src/eventray/node_modules/karma-coverage-allsources/node_modules/esprima/esprima.js:4972:16)
    at parsePrimaryExpression (/Users/sontek/src/eventray/node_modules/karma-coverage-allsources/node_modules/esprima/esprima.js:3232:24)
    at inheritCoverGrammar (/Users/sontek/src/eventray/node_modules/karma-coverage-allsources/node_modules/esprima/esprima.js:2648:18)
    at parseLeftHandSideExpressionAllowCall (/Users/sontek/src/eventray/node_modules/karma-coverage-allsources/node_modules/esprima/esprima.js:3373:20)
    at inheritCoverGrammar (/Users/sontek/src/eventray/node_modules/karma-coverage-allsources/node_modules/esprima/esprima.js:2648:18)
    at parsePostfixExpression (/Users/sontek/src/eventray/node_modules/karma-coverage-allsources/node_modules/esprima/esprima.js:3449:16)
    at parseUnaryExpression (/Users/sontek/src/eventray/node_modules/karma-coverage-allsources/node_modules/esprima/esprima.js:3509:20)
    at inheritCoverGrammar (/Users/sontek/src/eventray/node_modules/karma-coverage-allsources/node_modules/esprima/esprima.js:2648:18)
    at parseBinaryExpression (/Users/sontek/src/eventray/node_modules/karma-coverage-allsources/node_modules/esprima/esprima.js:3598:16)
    at inheritCoverGrammar (/Users/sontek/src/eventray/node_modules/karma-coverage-allsources/node_modules/esprima/esprima.js:2648:18)
    at parseConditionalExpression (/Users/sontek/src/eventray/node_modules/karma-coverage-allsources/node_modules/esprima/esprima.js:3655:16)
  index: 15,
  lineNumber: 1,
  column: 16,
  description: 'Unexpected token' }
```

**Comment by sontek** [comment] 2016-08-20 21:44
@mattfysh Also would be interested if you have any feedback on that.

**Comment by mattfysh** [comment] 2016-08-20 21:53
@sontek is your source code being transpiled by any chance? the allsources package works only with ES5 as it uses istanbul directly. if your code is ES6, it needs to be instrumented with https://github.com/istanbuljs/babel-plugin-istanbul - but the current hack doesn't support this. lmk if this is the issue, I'd be happy to see how we could get allsources support added directly to `karma-coverage` itself, plus support choice of instrumentation tool

**Comment by sontek** [comment] 2016-08-20 21:55
@mattfysh Yeah, thats exactly the issue. I've instrumented it with `babel-plugin-istanbul` because I'm using ES6

**Comment by kane-c** [comment] 2016-08-20 23:06
I use `babel-plugin-istanbul` too and haven't been able to get `karma-allsources` to work. I also use `karma-webpack`. My solution is to instead include a test file that simply imports every other source file.

For example, assuming your tests and sources are in the same folder, add a file named something like `all.test.js` with the contents:
```js
const context = require.context('.', true, /\.js$/);
context.keys().forEach(context);
```

**Comment by jseminck** [comment] 2016-08-21 08:18
I **thought** I got this karma-allsources to work correctly, but turns out I did not. No idea what happened... a brain fart I guess. :)

In the end we ended up doing the same as @kane-c, as we also use `babel-plugin-istanbul` and `karma-webpack`.

**Comment by sontek** [comment] 2016-08-21 14:12
@jseminck @kane-c Is that the only code you have in your `all.test.js` file to get everything imported?  I tried that and it was blowing up as well, I think I need to blacklist some files, it seems to have issues before webpack even runs:

```
21 08 2016 10:10:21.854:ERROR [karma]: { Error: no such file or directory
    at MemoryFileSystem.readFileSync (/Users/sontek/src/eventray/node_modules/memory-fs/lib/MemoryFileSystem.js:107:10)
    at MemoryFileSystem.readFile (/Users/sontek/src/eventray/node_modules/memory-fs/lib/MemoryFileSystem.js:297:21)
    at doRead (/Users/sontek/src/eventray/node_modules/karma-webpack/lib/karma-webpack.js:201:29)
    at Plugin.readFile (/Users/sontek/src/eventray/node_modules/karma-webpack/lib/karma-webpack.js:205:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  code: 'ENOENT',
  errno: 34,
  message: 'no such file or directory',
  path: '/_karma_webpack_/static/js/materials/card.test.js' }
21 08 2016 10:10:21.880:ERROR [karma]: { Error: no such file or directory
    at MemoryFileSystem.readFileSync (/Users/sontek/src/eventray/node_modules/memory-fs/lib/MemoryFileSystem.js:107:10)
    at MemoryFileSystem.readFile (/Users/sontek/src/eventray/node_modules/memory-fs/lib/MemoryFileSystem.js:297:21)
    at doRead (/Users/sontek/src/eventray/node_modules/karma-webpack/lib/karma-webpack.js:201:29)
    at Plugin.readFile (/Users/sontek/src/eventray/node_modules/karma-webpack/lib/karma-webpack.js:205:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at Immediate._tickDomainCallback (internal/process/next_tick.js:122:9)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)
  code: 'ENOENT',
  errno: 34,
  message: 'no such file or directory',
  path: '/_karma_webpack_/static/js/materials/button.test.js' }
21 08 2016 10:10:21.880:ERROR [karma]: { Error: no such file or directory
    at MemoryFileSystem.readFileSync (/Users/sontek/src/eventray/node_modules/memory-fs/lib/MemoryFileSystem.js:107:10)
    at MemoryFileSystem.readFile (/Users/sontek/src/eventray/node_modules/memory-fs/lib/MemoryFileSystem.js:297:21)
    at doRead (/Users/sontek/src/eventray/node_modules/karma-webpack/lib/karma-webpack.js:201:29)
    at Plugin.readFile (/Users/sontek/src/eventray/node_modules/karma-webpack/lib/karma-webpack.js:205:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  code: 'ENOENT',
  errno: 34,
  message: 'no such file or directory',
  path: '/_karma_webpack_/static/js/materials/header.test.js' }
```

and then after it runs:

```

WARNING in ./static/js \.js$
Module not found: Error: a dependency to an entry point is not allowed
 @ ./static/js \.js$

WARNING in ./~/fsevents/~/node-pre-gyp/lib/util/versioning.js
Critical dependencies:
15:20-67 the request of a dependency is an expression
 @ ./~/fsevents/~/node-pre-gyp/lib/util/versioning.js 15:20-67

WARNING in ./~/fsevents/~/node-pre-gyp/lib/util/compile.js
Module not found: Error: Cannot resolve module 'npm' in /Users/sontek/src/eventray/node_modules/fsevents/node_modules/node-pre-gyp/lib/util
 @ ./~/fsevents/~/node-pre-gyp/lib/util/compile.js 39:27-49

WARNING in ./~/fsevents/~/node-pre-gyp/lib/util/nw-pre-gyp/index.html
Module parse failed: /Users/sontek/src/eventray/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/nw-pre-gyp/index.html Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp$4.raise (/Users/sontek/src/eventray/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/sontek/src/eventray/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/Users/sontek/src/eventray/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/Users/sontek/src/eventray/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/Users/sontek/src/eventray/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/Users/sontek/src/eventray/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/Users/sontek/src/eventray/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/Users/sontek/src/eventray/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/Users/sontek/src/eventray/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseStatement (/Users/sontek/src/eventray/node_modules/acorn/dist/acorn.js:727:47)
    at Parser.pp$1.parseTopLevel (/Users/sontek/src/eventray/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/sontek/src/eventray/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/sontek/src/eventray/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/sontek/src/eventray/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/sontek/src/eventray/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/sontek/src/eventray/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
 @ ./~/fsevents/~/node-pre-gyp/lib/util ^\.\/.*$

WARNING in ./~/fsevents/~/node-pre-gyp/lib/pre-binding.js
Critical dependencies:
19:22-48 the request of a dependency is an expression
 @ ./~/fsevents/~/node-pre-gyp/lib/pre-binding.js 19:22-48

WARNING in ./~/fsevents/fsevents.js
Critical dependencies:
11:13-71 the request of a dependency is an expression
 @ ./~/fsevents/fsevents.js 11:13-71
```

**Comment by sontek** [comment] 2016-08-21 14:41
It looks like it was loading up my `webpack.config.js` and loading the tests that were already in there.  Doing something like this:

```
const context = require.context(
    '.', true, /.*[^test]\.jsx?$/
);
context.keys().forEach(context);
```

Which stopped it from loading the test files a second time and I put it away from my webpack.config.js, now my only issue is:

```
  Invariant Violation: _registerComponent(...): Target container is not a DOM element.
  at static/js/all.test.js:4127
```

Because one of my files (`index.js`) tries to render into the DOM on import.  Is there a way to blacklist certain files?

**Comment by sontek** [comment] 2016-08-21 14:49
I ended up renaming `index.js` something special so I could target it easily in the regex to ignore it.  Couldn't figure out how to do a filter function to ignore specific files.

**Comment by jseminck** [comment] 2016-08-21 18:08
I think our file structure is something like:
* /tests/
* /resources/
* index.js
* other_config.js

So we can easily just load the files separately: `/tests/*.js` and `/resources/*.js

**Comment by kane-c** [comment] 2016-08-22 01:24
@sontek You'll just need to play with the regex to get it to match the files you want to include. It can be a bit tedious; adjusting your file structure like @jseminck said is the easiest way!

**Comment by mattfysh** [comment] 2016-08-23 00:16
There are a couple of issues caused by using babel-plugin-istanbul with karma-coverage and a front-end bundler:

1. while karma-coverage allows you to configure which instrumenter can be used, it expects the final instrumented code to contain the coverage object in a particular format, which is not the output when using the babel plugin. See https://github.com/karma-runner/karma-coverage/blob/master/lib/preprocessor.js#L22

2. `includeAllSources` expects all source files to be preprocessed and instrumented by karma, when this is usually no longer true for users of _browserify_, _webpack_, _systemjs_, etc. Bundling and instrumentation for those users is typically done as part of the build process, e.g. _karma-browserify_.

The first thing you want to avoid is instrumenting the same file twice (once by karma-coverage, and the other by your bundler), however when not used as the instrumenter, karma-coverage isn't aware of which files have been instrumented until the test run has completed.

I was thinking of adding an option for lazy instrumentation, where pushing files through the preprocessor takes note of their path only, and during reporting it checks that each file has metrics reported. If not, it will instrument and report on the base coverage stats for missing files only.

**Comment by DrewZuk** [comment] 2017-01-09 19:56
Utilizing `karma-coverage-allsources`, it appears the reporter constructor fails to initialize the reporter instance with an empty array for the `adapters` property.  Karma seems to expect that this will be an array for any reporter you're using.  Anyone else experiencing this issue?  I'm using karma version 1.3.0.

**Comment by bsuh** [comment] 2018-04-29 16:07
For those using `babel-plugin-istanbul` and can upgrade to babel 7 beta @mattfysh @kane-c, here's my solution, which I find preferable to running all your source files.

We can add to the `coverageMap` of `karma-coverage` from `babel-plugin-istanbul`'s `onCover` callback using `.babelrc.js` (can't do it in JSON because you can't declare functions in JSON), which requires babel 7.

Make sure that your source files pass through babel and then my [`karma-null-preprocessor`](https://www.npmjs.com/package/karma-null-preprocessor) which simply [replaces the instrumented output from babel preprocessor with an empty string](https://github.com/bsuh/karma-null-preprocessor/blob/b8201774802fabc3113049fa3e50ff06d87537a7/index.js#L4-L8) so no code with side effects is run in the browser.

Lastly, be sure to set `includeAllSources` under `coverageReporter` to true so the reporter reads the baseline coverage from `coverageMap`.
```
modified   .babelrc.js
@@ -1,11 +1,17 @@
 const config = process.env.WEBPACK_CONFIG || 'debug';
+const coverageMap = require('karma-coverage/lib/coverage-map');
 
 const plugins = [
   '@babel/plugin-syntax-dynamic-import',
 ];
 
 if (config === 'test' && !('NO_COVERAGE' in process.env)) {
-  plugins.push(['istanbul', { exclude: '**/*.+(test|spec).+(js|jsx)' }]);
+  plugins.push(['istanbul', {
+    exclude: '**/*.+(test|spec).+(js|jsx)',
+    onCover: function (path, coverage) {
+      coverageMap.add(coverage);
+    },
+  }]);
 }
 
 const presetEnvOptions = {
modified   karma.conf.js
@@ -8,10 +8,11 @@ process.env.WEBPACK_CONFIG = 'test';
 // Karma configuration
 module.exports = function(config) {
   config.set({
-    files: [{ pattern: 'src/**/*.+(test|spec).+(js|jsx)' }],
+    files: [{ pattern: 'src/**/*.+(js|jsx)' }],
 
     preprocessors: {
       'src/**/*.+(test|spec).+(js|jsx)': ['webpack'],
+      'src/**/!(*.+(test|spec)).+(js|jsx)': ['babel', 'null'],
     },
 
     webpack: merge.strategy({ entry: 'replace', plugins: 'replace' })(
@@ -52,6 +53,7 @@ module.exports = function(config) {
     },
 
     coverageReporter: {
+      includeAllSources: true,
       dir: 'reports/coverage',
       reporters: [{ type: 'html', subdir: '.' }],
     },
```

**Comment by rcollette** [comment] 2019-01-25 16:08
The test.cs file that is distributed with Angular-cli can be modified to include all source files as shown in the `const context` line below.

```javascript
// This file is required by karma.conf.js and loads recursively all the .spec and framework files

import 'zone.js/dist/long-stack-trace-zone';
import 'zone.js/dist/proxy.js';
import 'zone.js/dist/sync-test';
import 'zone.js/dist/jasmine-patch';
import 'zone.js/dist/async-test';
import 'zone.js/dist/fake-async-test';
import { getTestBed } from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting
} from '@angular/platform-browser-dynamic/testing';

/** The order of imports matters! Commented the original order here just in case it gets messed by code re-ordering
import 'zone.js/dist/long-stack-trace-zone';
import 'zone.js/dist/proxy.js';
import 'zone.js/dist/sync-test';
import 'zone.js/dist/jasmine-patch';
import 'zone.js/dist/async-test';
import 'zone.js/dist/fake-async-test';
import { getTestBed } from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting
} from '@angular/platform-browser-dynamic/testing';
 **/

// Unfortunately there's no typing for the `__karma__` variable. Just declare it as any.
declare const __karma__: any;
declare const require: any;

// Prevent Karma from running prematurely.
__karma__.loaded = function () {};

// First, initialize the Angular testing environment.
getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting()
);

// Then we find all the tests.
// The following was the original but does not indicate missing coverage for files which do not have an
// associated .spec.ts file which imports the source.
// const context = require.context('./', true, /\.spec\.ts$/);

// The following was added to indicate coverage on all files.
// Do not re-order imports when editing this file!!
const context = require.context('./', true, /\/app\/.*\.ts$/);
// And load the modules.
context.keys().map(context);
// Finally, start Karma to run the tests.
__karma__.start();
```

**Comment by kopach** [comment] 2019-12-09 22:47
Hi guys. For anyone still interested in this topic, I've built a tool (seems to be similar to `karma-coverage-allsources`) which helps to add untested file to coverage report. It works fine with ES6 and TypeScript files. Fell free to use it and give your feedback. https://github.com/kopach/karma-sabarivka-reporter
